spring:
  application:
    name: order
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
        max-attempts: 10
        initial-interval: 1000