spring:
  application:
    name: warehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home?currentSchema=warehouse
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5 # Ускоряем получение реестра
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 5  # Heartbeats каждые 5 секунд
    lease-expiration-duration-in-seconds: 10 # Истечение аренды через 10 секунд
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data: INFO
    ru.yandex.practicum.commerce.warehouse: INFO