server:
  port: 8080

spring:
  application:
    name: collector
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.kafka.telemetry.collector.serialization.AvroSerializer