spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home?currentSchema=payment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: payment
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.boot.autoconfigure.sql: DEBUG
    ru.yandex.practicum.commerce: DEBUG