server:
  port: 8081

spring:
  application:
    name: aggregator
  jackson:
    time-zone: UTC

kafka:
  bootstrap-servers: localhost:9092
  sensor-events-topic: telemetry.sensors.v1
  snapshots-topic: telemetry.snapshots.v1