spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: analyzer-group
      auto-offset-reset: earliest
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}
        specific.avro.reader: true
    listener:
      type: batch
kafka:
  topics:
    snapshots: telemetry.snapshots.v1
    hub: telemetry.hubs.v1
  consumer:
    group-id:
      snapshots: analyzer.snapshots
      hub: analyzer.hubs
grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
logging:
  level:
    ru.yandex.practicum: DEBUG
    net.devh.boot.grpc: DEBUG
    io.grpc: DEBUG
    org.springframework.core.env: DEBUG # Для отладки свойств
    org.springframework.boot.context.properties: DEBUG # Для отладки профилей