server:
  port: 8080

spring:
  application:
    name: collector
  jackson:
    time-zone: UTC

kafka:
  bootstrap-servers: localhost:9092
  hub-events-topic: telemetry.hubs.v1
  sensor-events-topic: telemetry.sensors.v1

grpc:
  server:
    port: 9090